server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: counter1
        uri: http://localhost:9080
        predicates:
        - Path=/counter
        - Weight=counter, 95
      - id: counter2
        uri: http://localhost:9081
        predicates:
        - Path=/counter
        - Weight=counter, 5

management:
  endpoint:
    prometheus:
      enabled=true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled=true

build:
  version: @project.version@

handleError: true
